USERNAME        = 'username'
PASSWORD        = 'password'
UPDATED_AT      = 'updated_at'
EXPIRES_AT      = 'expires_at'
CREATED_AT      = 'created_at'
ACTIVE          = 'active'
LOGINS_COUNT    = 'logins_count'
SU              = 'su'

INFO            = 'info'
WARNING         = 'warning'
SUCCESS         = 'success'
ERROR           = 'error'
